### PR TITLE
recalculate all route segments

### PR DESCRIPTION
**Pull request by nrenner**
Adds a public method routeAllSegments to recalculate the complete route by routing each segment.

Use-case is to update the route after routing options like profile (mode of transport) have been changed by the user.

Another way to update the route would be to send a single request with all waypoints and split the result into segments. Probably depends on what the routing engine supports. Leaving that as a task for later.

### CODE REVIEW

**Comment by Starefossen** [comment]
Sorry for the delay on this one @nrenner. If you could rename the `routeAllSegments()` method to `rerouteAllSegments()` I will merge this in right away. Thanks a lot for your contributions!

**Comment by nrenner** [comment]
Don't worry, I'm in no hurry. Rename done.

**Comment by nrenner** [comment]
Thanks a lot for providing this library!

I'm using it in [brouter-web](https://github.com/nrenner/brouter-web) and now there is also an [online service](http://h2096617.stratoserver.net/brouter-web/) hosted at the BRouter site.

**Comment by Starefossen** [comment]
No problem @nrenner! We at the Norwegian Trekking Association are very happy to contribute to the open course community.

**Pull request merged**
